export const SHOP_CATEGORIES = [
  { id: 'all', label: 'All Categories', count: 86 },
  { id: 'dresses', label: 'Dresses', count: 24 },
  { id: 'tops', label: 'Tops', count: 18 },
  { id: 'coords', label: 'Co-ord Sets', count: 14 },
  { id: 'ethnic', label: 'Ethnic Wear', count: 16 },
  { id: 'lounge', label: 'Lounge Wear', count: 8 },
  { id: 'nightwear', label: 'Nightwear', count: 6 },
]

export const SHOP_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL']

export const SHOP_COLORS = [
  { id: 'rose', label: 'Dusty Rose', hex: '#AD4A85' },
  { id: 'cream', label: 'Cream', hex: '#F5E6D3' },
  { id: 'beige', label: 'Beige', hex: '#D4B896' },
  { id: 'sage', label: 'Sage', hex: '#A8B89A' },
  { id: 'mauve', label: 'Mauve', hex: '#C57BA3' },
  { id: 'black', label: 'Black', hex: '#2A1A22' },
  { id: 'blush', label: 'Blush', hex: '#EFD7E3' },
  { id: 'wine', label: 'Wine', hex: '#8E3466' },
]

export const SHOP_FILTER_OPTIONS = {
  availability: ['In Stock', 'Made to Order'],
  discount: ['10% & Above', '20% & Above', '30% & Above', '40% & Above'],
  sleeve: ['Sleeveless', 'Short Sleeve', '3/4 Sleeve', 'Full Sleeve'],
  fabric: ['Cotton', 'Linen', 'Satin', 'Georgette', 'Rayon', 'Silk Blend'],
  occasion: ['Casual', 'Work', 'Party', 'Festive', 'Lounge'],
  fit: ['Regular', 'Relaxed', 'Slim', 'Oversized'],
  pattern: ['Solid', 'Floral', 'Printed', 'Embroidered', 'Striped'],
  season: ['Summer', 'Monsoon', 'Winter', 'All Season'],
  ratings: ['4★ & Above', '3★ & Above'],
  brand: ['JALYN Essentials', 'JALYN Luxe', 'JALYN Studio'],
}

export const PRICE_BOUNDS = { min: 499, max: 4999 }

/** @type {Array<Record<string, any>>} */
export const SHOP_PRODUCTS = [
  {
    id: 'sp1',
    slug: 'floral-midi-dress',
    title: 'Floral Midi Dress',
    category: 'dresses',
    images: {
      primary:
        'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
    },
    price: 1899,
    originalPrice: 2499,
    discount: 24,
    rating: 4.8,
    reviews: 124,
    colors: ['rose', 'cream', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 18,
    badges: ['new'],
    description: 'Soft floral midi with a fluid silhouette for everyday elegance.',
    fabric: 'Georgette',
    sleeve: 'Short Sleeve',
    occasion: 'Casual',
    fit: 'Regular',
    pattern: 'Floral',
    season: 'Summer',
    brand: 'JALYN Essentials',
  },
  {
    id: 'sp2',
    slug: 'satin-slip-dress',
    title: 'Satin Slip Dress',
    category: 'dresses',
    images: {
      primary:
        'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=800&q=80',
    },
    price: 2199,
    originalPrice: 2799,
    discount: 21,
    rating: 4.7,
    reviews: 89,
    colors: ['mauve', 'black', 'wine'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 12,
    badges: ['new', 'sale'],
    description: 'Liquid satin slip dress made for evenings that linger.',
    fabric: 'Satin',
    sleeve: 'Sleeveless',
    occasion: 'Party',
    fit: 'Slim',
    pattern: 'Solid',
    season: 'All Season',
    brand: 'JALYN Luxe',
  },
  {
    id: 'sp3',
    slug: 'linen-wrap-top',
    title: 'Linen Wrap Top',
    category: 'tops',
    images: {
      primary:
        'https://images.unsplash.com/photo-1551163943-3f6fa0d40dc1?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=800&q=80',
    },
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    rating: 4.9,
    reviews: 156,
    colors: ['cream', 'beige', 'sage'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 32,
    badges: [],
    description: 'Breathable linen wrap top for effortless daywear.',
    fabric: 'Linen',
    sleeve: '3/4 Sleeve',
    occasion: 'Work',
    fit: 'Relaxed',
    pattern: 'Solid',
    season: 'Summer',
    brand: 'JALYN Essentials',
  },
  {
    id: 'sp4',
    slug: 'pleated-mauve-dress',
    title: 'Pleated Mauve Dress',
    category: 'dresses',
    images: {
      primary:
        'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1598554747436-c9293d6a477c?auto=format&fit=crop&w=800&q=80',
    },
    price: 2499,
    originalPrice: 3199,
    discount: 22,
    rating: 4.8,
    reviews: 203,
    colors: ['mauve', 'rose', 'blush'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 9,
    badges: ['new', 'limited'],
    description: 'Editorial pleats in a soft mauve for elevated comfort.',
    fabric: 'Georgette',
    sleeve: 'Full Sleeve',
    occasion: 'Work',
    fit: 'Regular',
    pattern: 'Solid',
    season: 'All Season',
    brand: 'JALYN Luxe',
  },
  {
    id: 'sp5',
    slug: 'soft-knit-coord',
    title: 'Soft Knit Co-ord',
    category: 'coords',
    images: {
      primary:
        'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
    },
    price: 2799,
    originalPrice: 3499,
    discount: 20,
    rating: 4.6,
    reviews: 67,
    colors: ['beige', 'cream', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 14,
    badges: ['new'],
    description: 'Matching knit set for polished lounge-to-street looks.',
    fabric: 'Cotton',
    sleeve: 'Full Sleeve',
    occasion: 'Casual',
    fit: 'Relaxed',
    pattern: 'Solid',
    season: 'Winter',
    brand: 'JALYN Studio',
  },
  {
    id: 'sp6',
    slug: 'embroidered-kurta',
    title: 'Embroidered Kurta',
    category: 'ethnic',
    images: {
      primary:
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    },
    price: 2299,
    originalPrice: 2999,
    discount: 23,
    rating: 4.7,
    reviews: 98,
    colors: ['cream', 'rose', 'wine'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 21,
    badges: ['sale'],
    description: 'Light ethnic kurta with delicate embroidery details.',
    fabric: 'Cotton',
    sleeve: '3/4 Sleeve',
    occasion: 'Festive',
    fit: 'Regular',
    pattern: 'Embroidered',
    season: 'All Season',
    brand: 'JALYN Essentials',
  },
  {
    id: 'sp7',
    slug: 'maxi-flare-dress',
    title: 'Maxi Flare Dress',
    category: 'dresses',
    images: {
      primary:
        'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
    },
    price: 2699,
    originalPrice: 3499,
    discount: 23,
    rating: 4.5,
    reviews: 74,
    colors: ['rose', 'blush', 'black'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 7,
    badges: ['limited'],
    description: 'Flowy maxi dress for garden evenings and celebrations.',
    fabric: 'Georgette',
    sleeve: 'Short Sleeve',
    occasion: 'Party',
    fit: 'Relaxed',
    pattern: 'Floral',
    season: 'Summer',
    brand: 'JALYN Luxe',
  },
  {
    id: 'sp8',
    slug: 'office-shirt-dress',
    title: 'Office Shirt Dress',
    category: 'dresses',
    images: {
      primary:
        'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
    },
    price: 1999,
    originalPrice: 2599,
    discount: 23,
    rating: 4.6,
    reviews: 112,
    colors: ['beige', 'black', 'sage'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 25,
    badges: [],
    description: 'Structured shirt dress for polished workdays.',
    fabric: 'Cotton',
    sleeve: 'Full Sleeve',
    occasion: 'Work',
    fit: 'Slim',
    pattern: 'Solid',
    season: 'All Season',
    brand: 'JALYN Studio',
  },
  {
    id: 'sp9',
    slug: 'cloud-lounge-set',
    title: 'Cloud Lounge Set',
    category: 'lounge',
    images: {
      primary:
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    },
    price: 1799,
    originalPrice: 2299,
    discount: 22,
    rating: 4.9,
    reviews: 188,
    colors: ['blush', 'cream', 'mauve'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 40,
    badges: ['new'],
    description: 'Ultra-soft lounge set for slow mornings at home.',
    fabric: 'Cotton',
    sleeve: 'Short Sleeve',
    occasion: 'Lounge',
    fit: 'Oversized',
    pattern: 'Solid',
    season: 'All Season',
    brand: 'JALYN Essentials',
  },
  {
    id: 'sp10',
    slug: 'silk-nightwear-set',
    title: 'Silk Nightwear Set',
    category: 'nightwear',
    images: {
      primary:
        'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80',
    },
    price: 2499,
    originalPrice: 3299,
    discount: 24,
    rating: 4.4,
    reviews: 51,
    colors: ['wine', 'black', 'blush'],
    sizes: ['S', 'M', 'L'],
    stock: 11,
    badges: ['sale'],
    description: 'Soft silk-touch nightwear for restful evenings.',
    fabric: 'Silk Blend',
    sleeve: 'Short Sleeve',
    occasion: 'Lounge',
    fit: 'Relaxed',
    pattern: 'Solid',
    season: 'All Season',
    brand: 'JALYN Luxe',
  },
  {
    id: 'sp11',
    slug: 'fusion-anarkali-top',
    title: 'Fusion Anarkali Top',
    category: 'ethnic',
    images: {
      primary:
        'https://images.unsplash.com/photo-1598554747436-c9293d6a477c?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?auto=format&fit=crop&w=800&q=80',
    },
    price: 1899,
    originalPrice: 2399,
    discount: 21,
    rating: 4.7,
    reviews: 83,
    colors: ['rose', 'cream', 'mauve'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 16,
    badges: ['new'],
    description: 'Contemporary fusion top with graceful anarkali lines.',
    fabric: 'Rayon',
    sleeve: '3/4 Sleeve',
    occasion: 'Festive',
    fit: 'Regular',
    pattern: 'Printed',
    season: 'Monsoon',
    brand: 'JALYN Studio',
  },
  {
    id: 'sp12',
    slug: 'party-sequin-top',
    title: 'Party Sequin Top',
    category: 'tops',
    images: {
      primary:
        'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
      hover:
        'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
    },
    price: 1599,
    originalPrice: 2199,
    discount: 27,
    rating: 4.3,
    reviews: 45,
    colors: ['black', 'wine', 'rose'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 8,
    badges: ['sale', 'limited'],
    description: 'Statement sequin top for nights out and celebrations.',
    fabric: 'Satin',
    sleeve: 'Sleeveless',
    occasion: 'Party',
    fit: 'Slim',
    pattern: 'Solid',
    season: 'Winter',
    brand: 'JALYN Luxe',
  },
]
